server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource: 
    password: Kavya@123
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jpa.dialect: org.hibernate.dialect.MySQL5%Dialect
        format_sql: true
    show-sql: true
  datasource.driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: localhost
    port: 8089
    username: root
    password: Kavya@123

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000